sudo: false
language: go
go:
  - 1.8
install:
  - go get -u github.com/jstemmer/go-junit-report
  - go get -u github.com/golang/dep/...
  - go get -u github.com/Masterminds/glide
  - glide update
script:
  - make ci-test
  - make ci-vet
