sudo: false
language: go
go:
  - 1.7.4
env:
  global:
    IMPORT_PATH="github.com/${TRAVIS_REPO_SLUG}"
    WORK_DIR="~/gopath"
install:
  - go get -u github.com/jstemmer/go-junit-report
  - go get -u github.com/golang/dep/...
  - go get -u github.com/Masterminds/glide
  - glide update
script:
  - make ci-test
  - make ci-vet
