sudo: false
language: go
go:
  - 1.7.4
env:
  global:
    IMPORT_PATH="github.com/${TRAVIS_REPO_SLUG}"
    WORK_DIR="${HOME}/gopath"
    CIRCLE_TEST_REPORTS="${HOME}/reports"
install:
  - go get -u github.com/jstemmer/go-junit-report
  - go get -u github.com/golang/dep/...
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/golang/lint/golint
  - glide update
  - mkdir -p $CIRCLE_TEST_REPORTS/golang 
script:
  - make ci-test
  - make ci-vet
  - make ci-lint
