version: '2'
services:
  app:
    image: golang:1.8.0-alpine
    command: ./bin/run.sh
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/github.com/shinofara/simple-go-web-app"
    working_dir: "/go/src/github.com/shinofara/simple-go-web-app"
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
