version: '2'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
